# Generated by Django 2.0.6 on 2019-04-05 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_userinfotable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfotable',
            name='tbusermob',
            field=models.CharField(max_length=255),
        ),
    ]
