# Generated by Django 2.0.6 on 2019-04-10 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_auto_20190405_1526'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBrand',
            fields=[
                ('tbbrandid', models.AutoField(primary_key=True, serialize=False)),
                ('tbbrandname', models.CharField(max_length=255, unique=True)),
                ('brand_is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('tbcategoryid', models.AutoField(primary_key=True, serialize=False)),
                ('tbcategorytype', models.CharField(max_length=255, unique=True)),
                ('category_is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductDetails',
            fields=[
                ('tbproductid', models.AutoField(primary_key=True, serialize=False)),
                ('tbproductname', models.CharField(max_length=255)),
                ('tbproductprice', models.IntegerField()),
                ('tbproductquantity', models.IntegerField()),
                ('tbproductdescription', models.CharField(max_length=255)),
                ('tbproductimage1', models.CharField(max_length=255)),
                ('tbproductimage2', models.CharField(max_length=255)),
                ('tbproductimage3', models.CharField(max_length=255)),
                ('tbproductimage4', models.CharField(max_length=255)),
                ('tbproductimage5', models.CharField(max_length=255)),
                ('tbproductimage6', models.CharField(max_length=255)),
                ('tbproductimage7', models.CharField(max_length=255)),
                ('publishdate', models.CharField(max_length=255)),
                ('product_is_active', models.BooleanField(default=True)),
                ('fkproductbrandid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.ProductBrand')),
                ('fkproductcategoryid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.ProductCategory')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('tbproductsizeid', models.AutoField(primary_key=True, serialize=False)),
                ('tbproductsize', models.CharField(max_length=255)),
                ('size_is_active', models.BooleanField(default=True)),
                ('tbcategoryid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.ProductCategory')),
            ],
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('tbproducttypeid', models.AutoField(primary_key=True, serialize=False)),
                ('tbproducttypename', models.CharField(max_length=255, unique=True)),
                ('type_is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='userinfotable',
            name='tbuserpan',
            field=models.CharField(default='pan', max_length=255),
        ),
        migrations.AddField(
            model_name='productdetails',
            name='fkproductsizeid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.ProductSize'),
        ),
        migrations.AddField(
            model_name='productdetails',
            name='fkproducttypeid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.ProductType'),
        ),
        migrations.AddField(
            model_name='productdetails',
            name='tbuseremail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.UserInfoTable'),
        ),
    ]
