# Generated by Django 2.0.6 on 2019-04-16 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_auto_20190410_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdetails',
            name='fkproductcategoryid',
        ),
        migrations.RemoveField(
            model_name='productdetails',
            name='fkproductsizeid',
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='tbproductimage2',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='tbproductimage3',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='tbproductimage4',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='tbproductimage5',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='tbproductimage6',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='tbproductimage7',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
