# Generated by Django 2.0.6 on 2019-04-16 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_auto_20190416_1830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsize',
            name='tbcategoryid',
        ),
    ]
