# Generated by Django 2.0.6 on 2019-04-16 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_remove_productsize_tbcategoryid'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetails',
            name='fkproductcategoryid',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='manager.ProductCategory'),
        ),
        migrations.AddField(
            model_name='productdetails',
            name='fkproductsizeid',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='manager.ProductSize'),
        ),
        migrations.AddField(
            model_name='productsize',
            name='tbcategoryid',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='manager.ProductCategory'),
        ),
    ]
