# Generated by Django 2.0.6 on 2019-04-16 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_auto_20190416_1834'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSubCategory',
            fields=[
                ('tbsubcategoryid', models.AutoField(primary_key=True, serialize=False)),
                ('tbsubcategoryname', models.CharField(max_length=255)),
                ('fkcategoryid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.ProductCategory')),
                ('fksizeid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.ProductSize')),
            ],
        ),
        migrations.AddField(
            model_name='productdetails',
            name='fksubcategoryid',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='manager.ProductSubCategory'),
        ),
    ]
