# Generated by Django 2.0.6 on 2019-04-17 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_auto_20190416_1909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsubcategory',
            name='fksizeid',
        ),
        migrations.AlterField(
            model_name='productsubcategory',
            name='tbsubcategoryname',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
