# Generated by Django 2.0.6 on 2019-04-18 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0009_auto_20190417_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfotable',
            name='tbauthtoken',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userinfotable',
            name='tbisverified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userinfotable',
            name='tbotp',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userinfotable',
            name='tbotptime',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userinfotable',
            name='tbuseradhar',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userinfotable',
            name='tbuserpan',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
