# Generated by Django 2.0.6 on 2019-04-18 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0010_auto_20190418_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductStock',
            fields=[
                ('tbproductstockid', models.AutoField(primary_key=True, serialize=False)),
                ('productquantity', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='productdetails',
            name='fkproductsizeid',
        ),
        migrations.AddField(
            model_name='productstock',
            name='fkproductid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.ProductDetails'),
        ),
        migrations.AddField(
            model_name='productstock',
            name='fkproductsizeid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.ProductSize'),
        ),
    ]
