# Generated by Django 2.0.6 on 2019-04-18 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0011_auto_20190419_0044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productstock',
            old_name='productquantity',
            new_name='tbproductquantity',
        ),
        migrations.AddField(
            model_name='productstock',
            name='stock_is_active',
            field=models.BooleanField(default=True),
        ),
    ]
